-- Solari 3D box: catalogue et simulations publics.
-- Executer ce script dans Supabase > SQL Editor.
-- Toute personne disposant de l'URL de l'application peut lire, creer,
-- modifier et supprimer ces donnees : c'est le comportement demande.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 120),
  length_mm integer not null check (length_mm > 0 and length_mm <= 100000),
  width_mm integer not null check (width_mm > 0 and width_mm <= 100000),
  height_mm integer not null check (height_mm > 0 and height_mm <= 100000),
  created_at timestamptz not null default now()
);

create table if not exists public.simulations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 160),
  optimization_mode text not null check (optimization_mode in ('manual', 'auto')),
  auto_container_type_indexes jsonb not null default '[]'::jsonb check (jsonb_typeof(auto_container_type_indexes) = 'array'),
  containers jsonb not null default '[]'::jsonb check (jsonb_typeof(containers) = 'array'),
  boxes jsonb not null default '[]'::jsonb check (jsonb_typeof(boxes) = 'array'),
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_name_dimensions_key'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_name_dimensions_key
      unique (name, length_mm, width_mm, height_mm);
  end if;
end $$;

create index if not exists products_name_idx on public.products (name);
create index if not exists simulations_created_at_idx on public.simulations (created_at desc);

alter table public.products enable row level security;
alter table public.simulations enable row level security;

revoke all on table public.products, public.simulations from anon, authenticated;
grant select, insert, update, delete on table public.products, public.simulations to anon;
grant usage, select on sequence public.products_id_seq, public.simulations_id_seq to anon;

drop policy if exists "public products select" on public.products;
drop policy if exists "public products insert" on public.products;
drop policy if exists "public products update" on public.products;
drop policy if exists "public products delete" on public.products;
create policy "public products select" on public.products for select to anon using (true);
create policy "public products insert" on public.products for insert to anon with check (true);
create policy "public products update" on public.products for update to anon using (true) with check (true);
create policy "public products delete" on public.products for delete to anon using (true);

drop policy if exists "public simulations select" on public.simulations;
drop policy if exists "public simulations insert" on public.simulations;
drop policy if exists "public simulations update" on public.simulations;
drop policy if exists "public simulations delete" on public.simulations;
create policy "public simulations select" on public.simulations for select to anon using (true);
create policy "public simulations insert" on public.simulations for insert to anon with check (true);
create policy "public simulations update" on public.simulations for update to anon using (true) with check (true);
create policy "public simulations delete" on public.simulations for delete to anon using (true);

-- Catalogue connu : une seule ligne par serie et dimensions de colisage.
-- Les couleurs, prix, versions et autres donnees commerciales ne sont pas enregistres.
insert into public.products (name, length_mm, width_mm, height_mm) values
  ('CFORCE 110', 1495, 1096, 619),
  ('CFORCE 520 L EPS', 2310, 1200, 850),
  ('U6 EV', 2925, 1490, 1950),
  ('UFORCE 600 EPS MY25', 2905, 1631, 1250),
  ('UFORCE 1000 EPS', 2930, 1930, 1250),
  ('UFORCE 1000 XL EPS', 3770, 1615, 1200),
  ('125NK', 2130, 590, 1070),
  ('450MT', 2250, 720, 1245),
  ('450NK', 2090, 766, 1180),
  ('450SR-S', 2150, 750, 1200),
  ('450CL-C', 2285, 790, 1180),
  ('800NK ADVANCED', 2240, 786, 1220),
  ('800MT EXPLORE', 2275, 820, 1200),
  ('675SR', 2165, 750, 1145),
  ('AE7 Pro', 1826, 735, 1105)
on conflict (name, length_mm, width_mm, height_mm) do nothing;

